/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tactical: {
          canvas: '#07090E',
          bg: '#07090E',
          panel: '#0C1017',
          surface: '#121721',
          raised: '#1A212E',
          border: '#1F2735',
          'border-active': '#2E3A4E',
          'border-focus': '#475874',
          muted: '#728299',
          text: '#E1E7EF',
          bright: '#F8FAFC',
        },
        phosphor: {
          green: '#10B981',
          'green-deep': '#059669',
          'green-glow': '#34D399',
          amber: '#F59E0B',
          'amber-hover': '#FBBF24',
          'amber-deep': '#D97706',
          red: '#EF4444',
          'red-deep': '#DC2626',
          cyan: '#38BDF8',
          'cyan-deep': '#0284C7',
          'cyan-glow': '#7DD3FC',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        mono: [
          '"JetBrains Mono"',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
    },
  },
  plugins: [],
};
