import {
  buildStatus,
  parseJestReport,
  renderDetail,
  renderSummary,
  replaceBlock,
} from '../../scripts/ci/generate-status';

const repoRoot = '/repo';
const jestReport = (overrides: any = {}) => ({
  numTotalTestSuites: 2,
  numPassedTestSuites: 1,
  numFailedTestSuites: 1,
  numTotalTests: 3,
  numPassedTests: 2,
  numFailedTests: 1,
  numPendingTests: 0,
  numTodoTests: 0,
  success: false,
  testResults: [
    {
      name: '/repo/backend/src/__tests__/b.test.ts',
      status: 'failed',
      assertionResults: [{ status: 'passed' }, { status: 'failed' }],
    },
    { name: '/repo/backend/src/__tests__/a.test.ts', status: 'passed', assertionResults: [{ status: 'passed' }] },
  ],
  ...overrides,
});

describe('P0.5 generate-status', () => {
  it('rejects input that is not a Jest --json report', () => {
    expect(() => parseJestReport('backend', { hello: 'world' }, repoRoot)).toThrow(/not a Jest --json report/);
  });

  it('carries failures through honestly (never rounds a failing run up to PASS)', () => {
    const p = parseJestReport('backend', jestReport(), repoRoot);
    expect(p.success).toBe(false);
    expect(p.tests).toEqual({ total: 3, passed: 2, failed: 1, skipped: 0 });
    expect(p.suiteDetails.map((s) => s.file)).toEqual(['backend/src/__tests__/a.test.ts', 'backend/src/__tests__/b.test.ts']);
    const status = buildStatus([p], 'abc123def4567890', 'unit-test', '2026-09-26T00:00:00.000Z');
    expect(status.allPassed).toBe(false);
    expect(renderSummary(status)).toContain('**FAIL**');
    expect(renderDetail(status)).toContain('| `backend/src/__tests__/b.test.ts` | 1 | 1 | 0 | FAILED |');
  });

  it('treats success:true with zero failures as PASS', () => {
    const p = parseJestReport(
      'ai-worker',
      jestReport({ numFailedTestSuites: 0, numPassedTestSuites: 2, numFailedTests: 0, numPassedTests: 3, success: true }),
      repoRoot
    );
    expect(p.success).toBe(true);
  });

  it('replaces only the marked block and refuses documents without markers', () => {
    const start =
      '<!-- TEST_STATUS:START (generated by backend/scripts/ci/generate-status.ts from a real Jest run; do not edit by hand) -->';
    const doc = `head\n${start}\nold\n<!-- TEST_STATUS:END -->\ntail`;
    expect(replaceBlock(doc, 'new')).toBe(`head\n${start}\nnew\n<!-- TEST_STATUS:END -->\ntail`);
    expect(() => replaceBlock('no markers', 'x')).toThrow(/missing the TEST_STATUS/);
  });
});
