/**
 * P0.5: test status is generated from a real Jest run, never hand-typed.
 *
 * Input: Jest JSON reports (`jest --json --outputFile=<file>`) for the backend and the ai-worker.
 * Output:
 *   - docs/generated/TEST_STATUS.json  (machine-readable, per-suite)
 *   - docs/generated/TEST_STATUS.md    (human-readable)
 *   - the TEST_STATUS block in PROJECT_STATE.md (summary + pointer)
 *
 * The status workflow (.github/workflows/status.yml) runs this on master and commits the result;
 * humans and agents do not edit these outputs by hand. `--check` verifies that the committed
 * markdown outputs match the committed JSON (catches hand edits).
 *
 *   ts-node scripts/ci/generate-status.ts --backend <jest.json> --ai-worker <jest.json> [--source <url>]
 *   ts-node scripts/ci/generate-status.ts --check
 */
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

export interface SuiteStatus {
  file: string;
  status: 'passed' | 'failed' | 'other';
  passed: number;
  failed: number;
  skipped: number;
}

export interface ProjectStatus {
  name: string;
  suites: { total: number; passed: number; failed: number };
  tests: { total: number; passed: number; failed: number; skipped: number };
  success: boolean;
  suiteDetails: SuiteStatus[];
}

export interface GeneratedStatus {
  schema: 'vigilone.test-status.v1';
  generatedAt: string;
  commit: string;
  source: string;
  projects: ProjectStatus[];
  totals: { suites: number; tests: number; passed: number; failed: number; skipped: number };
  allPassed: boolean;
}

const START = '<!-- TEST_STATUS:START (generated by backend/scripts/ci/generate-status.ts from a real Jest run; do not edit by hand) -->';
const END = '<!-- TEST_STATUS:END -->';

export function parseJestReport(name: string, report: any, repoRoot: string): ProjectStatus {
  if (!report || typeof report.numTotalTests !== 'number' || !Array.isArray(report.testResults)) {
    throw new Error(`${name}: input is not a Jest --json report`);
  }
  const suiteDetails: SuiteStatus[] = report.testResults
    .map((r: any) => {
      const assertions: any[] = r.assertionResults || [];
      return {
        file: path.relative(repoRoot, r.name).split(path.sep).join('/'),
        status: r.status === 'passed' ? 'passed' : r.status === 'failed' ? 'failed' : 'other',
        passed: assertions.filter((a) => a.status === 'passed').length,
        failed: assertions.filter((a) => a.status === 'failed').length,
        skipped: assertions.filter((a) => a.status === 'pending' || a.status === 'skipped' || a.status === 'todo').length,
      } as SuiteStatus;
    })
    .sort((a: SuiteStatus, b: SuiteStatus) => a.file.localeCompare(b.file));
  return {
    name,
    suites: {
      total: report.numTotalTestSuites,
      passed: report.numPassedTestSuites,
      failed: report.numFailedTestSuites,
    },
    tests: {
      total: report.numTotalTests,
      passed: report.numPassedTests,
      failed: report.numFailedTests,
      skipped: (report.numPendingTests || 0) + (report.numTodoTests || 0),
    },
    success: report.success === true && report.numFailedTests === 0 && report.numFailedTestSuites === 0,
    suiteDetails,
  };
}

export function buildStatus(projects: ProjectStatus[], commit: string, source: string, generatedAt: string): GeneratedStatus {
  const totals = projects.reduce(
    (acc, p) => ({
      suites: acc.suites + p.suites.total,
      tests: acc.tests + p.tests.total,
      passed: acc.passed + p.tests.passed,
      failed: acc.failed + p.tests.failed,
      skipped: acc.skipped + p.tests.skipped,
    }),
    { suites: 0, tests: 0, passed: 0, failed: 0, skipped: 0 }
  );
  return {
    schema: 'vigilone.test-status.v1',
    generatedAt,
    commit,
    source,
    projects,
    totals,
    allPassed: projects.every((p) => p.success),
  };
}

export function renderSummary(status: GeneratedStatus): string {
  const rows = status.projects.map(
    (p) =>
      `| ${p.name} | ${p.suites.passed}/${p.suites.total} | ${p.tests.passed}/${p.tests.total} | ${p.tests.failed} | ${p.tests.skipped} | ${p.success ? 'PASS' : 'FAIL'} |`
  );
  return [
    `Generated ${status.generatedAt} from commit \`${status.commit.slice(0, 12)}\` (${status.source}).`,
    '',
    '| Project | Suites passed | Tests passed | Failed | Skipped | Result |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
    `| **Total** | | **${status.totals.passed}/${status.totals.tests}** | **${status.totals.failed}** | **${status.totals.skipped}** | **${status.allPassed ? 'PASS' : 'FAIL'}** |`,
    '',
    'Per-suite detail: [`docs/generated/TEST_STATUS.md`](docs/generated/TEST_STATUS.md).',
  ].join('\n');
}

export function renderDetail(status: GeneratedStatus): string {
  const out = [
    '# Test status (generated)',
    '',
    '> Generated by `backend/scripts/ci/generate-status.ts` from real Jest `--json` output. Do not edit by hand;',
    '> CI regenerates it on every push to master.',
    '',
    renderSummary(status).replace('(docs/generated/TEST_STATUS.md)', '(TEST_STATUS.md)'),
    '',
  ];
  for (const p of status.projects) {
    out.push(`## ${p.name}`, '', '| Suite | Passed | Failed | Skipped | Status |', '| --- | --- | --- | --- | --- |');
    for (const s of p.suiteDetails) {
      out.push(`| \`${s.file}\` | ${s.passed} | ${s.failed} | ${s.skipped} | ${s.status.toUpperCase()} |`);
    }
    out.push('');
  }
  return out.join('\n');
}

export function replaceBlock(doc: string, body: string): string {
  const s = doc.indexOf(START);
  const e = doc.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    throw new Error('PROJECT_STATE.md is missing the TEST_STATUS:START/END markers');
  }
  return `${doc.slice(0, s)}${START}\n${body}\n${END}${doc.slice(e + END.length)}`;
}

function argValue(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

function main() {
  const repoRoot = path.resolve(__dirname, '../../..');
  const genDir = path.join(repoRoot, 'docs/generated');
  const jsonPath = path.join(genDir, 'TEST_STATUS.json');
  const mdPath = path.join(genDir, 'TEST_STATUS.md');
  const statePath = path.join(repoRoot, 'PROJECT_STATE.md');

  if (process.argv.includes('--check')) {
    const state = fs.readFileSync(statePath, 'utf8');
    if (!fs.existsSync(jsonPath)) {
      if (!state.includes(START) || !state.includes('PENDING_FIRST_CI_RUN')) {
        console.error('❌ No docs/generated/TEST_STATUS.json, and PROJECT_STATE.md does not show the pending marker.');
        process.exit(1);
      }
      console.log('ℹ️  No CI-generated test status yet (PENDING_FIRST_CI_RUN).');
      return;
    }
    const status: GeneratedStatus = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    const expectedMd = renderDetail(status);
    const expectedState = replaceBlock(state, renderSummary(status));
    const mdOk = fs.existsSync(mdPath) && fs.readFileSync(mdPath, 'utf8') === expectedMd;
    if (!mdOk || expectedState !== state) {
      console.error('❌ Generated test status was edited by hand or is out of sync with TEST_STATUS.json.');
      process.exit(1);
    }
    console.log('✅ Generated test status is consistent.');
    return;
  }

  const backendReport = argValue('--backend');
  const aiReport = argValue('--ai-worker');
  if (!backendReport || !aiReport) {
    console.error('Usage: generate-status.ts --backend <jest.json> --ai-worker <jest.json> [--source <text>]');
    process.exit(2);
  }
  const projects = [
    parseJestReport('backend', JSON.parse(fs.readFileSync(backendReport, 'utf8')), repoRoot),
    parseJestReport('ai-worker', JSON.parse(fs.readFileSync(aiReport, 'utf8')), repoRoot),
  ];
  const commit =
    process.env.GITHUB_SHA || execSync('git rev-parse HEAD', { cwd: repoRoot, encoding: 'utf8' }).trim();
  const source =
    argValue('--source') ||
    (process.env.GITHUB_RUN_ID
      ? `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
      : 'local run (not CI)');
  const status = buildStatus(projects, commit, source, new Date().toISOString());

  fs.mkdirSync(genDir, { recursive: true });
  fs.writeFileSync(jsonPath, JSON.stringify(status, null, 2) + '\n');
  fs.writeFileSync(mdPath, renderDetail(status));
  fs.writeFileSync(statePath, replaceBlock(fs.readFileSync(statePath, 'utf8'), renderSummary(status)));
  console.log(
    `Test status written: ${status.totals.passed}/${status.totals.tests} passed, ${status.totals.failed} failed (${status.allPassed ? 'PASS' : 'FAIL'}).`
  );
}

if (require.main === module) {
  main();
}
