/**
 * Regenerates the README scope table from the typed feature-flag registry so the README
 * cannot drift from what the code actually gates.
 *
 *   npm run docs:feature-flags          # rewrite README.md in place
 *   npm run docs:feature-flags -- --check  # CI: fail if README.md is stale
 */
import fs from 'fs';
import path from 'path';
import { renderFeatureFlagMarkdownTable } from '../../src/config/featureFlags';

const START = '<!-- FEATURE_FLAGS:START (generated by backend/scripts/ci/generate-feature-flag-docs.ts; do not edit by hand) -->';
const END = '<!-- FEATURE_FLAGS:END -->';

export function renderReadme(current: string): string {
  const startIdx = current.indexOf(START);
  const endIdx = current.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error('README.md is missing the FEATURE_FLAGS:START/END markers');
  }
  const block = `${START}\n${renderFeatureFlagMarkdownTable()}\n${END}`;
  return current.slice(0, startIdx) + block + current.slice(endIdx + END.length);
}

function main() {
  const readmePath = path.resolve(__dirname, '../../../README.md');
  const current = fs.readFileSync(readmePath, 'utf8');
  const next = renderReadme(current);
  if (process.argv.includes('--check')) {
    if (next !== current) {
      console.error('❌ README.md feature-flag table is stale. Run: cd backend && npm run docs:feature-flags');
      process.exit(1);
    }
    console.log('✅ README.md feature-flag table matches src/config/featureFlags.ts');
    return;
  }
  fs.writeFileSync(readmePath, next);
  console.log('README.md feature-flag table regenerated.');
}

if (require.main === module) {
  main();
}
