// GENERATED by sdk/ai-adapter/scripts/sync-contract.mjs from backend/src/contracts/common.ts. Do not edit here.
import { z } from 'zod';

/** ISO-8601 UTC timestamp with an explicit Z suffix (no local offsets on the wire). */
export const UtcTimestamp = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?Z$/, 'must be an ISO-8601 UTC timestamp ending in Z')
  .refine((s) => !Number.isNaN(Date.parse(s)), 'must be a valid date');

export const Sha256Hex = z.string().regex(/^[0-9a-f]{64}$/, 'must be a lowercase 64-hex SHA-256 digest');

export const NonEmptyId = z.string().min(1).max(200);

export const Confidence = z.number().finite().min(0).max(1);

/** Normalized [0,1] bounding box (x, y = top-left). */
export const NormalizedBox = z
  .object({
    x: z.number().finite().min(0).max(1),
    y: z.number().finite().min(0).max(1),
    width: z.number().finite().gt(0).max(1),
    height: z.number().finite().gt(0).max(1),
  })
  .strict()
  .refine((b) => b.x + b.width <= 1.000001 && b.y + b.height <= 1.000001, 'box must lie inside the frame');

/** Licences allowed inside the product (see THIRD_PARTY_LICENSES.md and check:model-licenses). */
export const PERMISSIVE_LICENSES = ['MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC'] as const;
export const PermissiveLicense = z.enum(PERMISSIVE_LICENSES);
/** One permissive licence, or several joined with " AND " (a pipeline of differently licensed models). */
export const PermissiveLicenseExpression = z
  .string()
  .refine((s) => s.split(' AND ').every((p) => (PERMISSIVE_LICENSES as readonly string[]).includes(p)), 'every part must be one of ' + PERMISSIVE_LICENSES.join(', '));
