#!/usr/bin/env node
/**
 * The worker runs its model pipelines on the adapter SDK's core (sdk/ai-adapter/src/core.ts, ADR 0007). The
 * worker image is built from its own package, so it ships a copy of the SDK core and the contract it needs in
 * src/sdk/. This copies them, or with --check fails when the copy differs (run in CI), so the two never drift.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, '../../../sdk/ai-adapter/src');
const dst = path.resolve(here, '../src/sdk');
const files = ['core.ts', 'contract/common.ts', 'contract/events.v1.ts', 'contract/aiAdapter.v1.ts'];
const header = (f) => `// GENERATED by services/ai-worker/scripts/sync-sdk.mjs from sdk/ai-adapter/src/${f}. Do not edit here.\n`;
const check = process.argv.includes('--check');
let drift = 0;
for (const f of files) {
  const want = header(f) + fs.readFileSync(path.join(src, f), 'utf8');
  const out = path.join(dst, f);
  if (check) {
    const have = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : null;
    if (have !== want) {
      console.error(`DRIFT: services/ai-worker/src/sdk/${f} differs from sdk/ai-adapter/src/${f}; run npm run sync-sdk`);
      drift++;
    }
  } else {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, want);
    console.log(`copied ${f}`);
  }
}
if (check) console.log(drift ? `${drift} SDK file(s) out of date` : 'worker SDK copy matches sdk/ai-adapter');
process.exit(drift ? 1 : 0);
