/**
 * incident-summary.v1: the fixed wording for incident summaries (ADR 0016).
 *
 * A pure function of the facts. `tools/vigilone-verify` carries an identical copy so an offline reader can re-render the
 * sentences from the facts; `incidentSummaryTemplateParity.test.ts` runs both on the same inputs and requires identical
 * output. Change the wording only by adding a new template version, never by editing this one: old records must keep
 * verifying.
 *
 * Rules the wording keeps: one sentence per fact (runs of earlier events or of detections share one), every sentence cites
 * the facts it states, and recorded text is quoted, stripped of control characters and capped, so it cannot add sentences
 * or pose as a citation. Plate text, operators' typed text and descriptions of people are never repeated.
 */
import { FactKind, IncidentSummaryFactsV1, INCIDENT_SUMMARY_TEMPLATE_V1, SummarySentence, TimelineFactV1 } from './types';

const MAX_TEXT = 200;
const clean = (v: unknown): string => String(v).replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, MAX_TEXT);
/** A recorded string, quoted. */
const q = (v: unknown): string => JSON.stringify(clean(v));
/** A recorded word (a class, a direction): cleaned and capped, not quoted. */
const w = (v: unknown): string => clean(v);
const num = (v: number): string => String(v);

export const CLOSING_STATEMENT_V1 = `This summary was generated by template ${INCIDENT_SUMMARY_TEMPLATE_V1} from the numbered recorded facts. It is not a model opinion; every statement cites the facts it rests on, and it does not by itself show that the event occurred.`;

type Fact<K extends FactKind> = Extract<TimelineFactV1, { kind: K }>;

export interface RenderedSummary {
  sentences: SummarySentence[];
  text: string;
}

export const joinSentences = (sentences: SummarySentence[]): string =>
  sentences.map((s) => (s.cites.length ? `${s.text} [${s.cites.join(', ')}]` : s.text)).join('\n');

export function renderIncidentSummaryV1(facts: IncidentSummaryFactsV1): RenderedSummary {
  const camName = new Map(facts.cameras.map((c) => [c.id, c.name]));
  const onCam = (id: string | null): string => (id ? ` on camera ${q(camName.get(id) ?? id)}` : '');
  const sentences: SummarySentence[] = [];
  const push = (text: string, ...cites: string[]) => sentences.push({ text, cites });

  const timeline = facts.timeline;
  for (let i = 0; i < timeline.length; i++) {
    const f = timeline[i];

    // Runs of earlier events, and of detections, share one sentence that cites each of them.
    if (f.kind === 'CORRELATED_EVENT' || f.kind === 'DETECTION') {
      const run: Array<Fact<'CORRELATED_EVENT'> | Fact<'DETECTION'>> = [];
      let j = i;
      while (j < timeline.length && timeline[j].kind === f.kind) run.push(timeline[j++] as any);
      if (f.kind === 'CORRELATED_EVENT') {
        push(`Earlier events in the same correlation chain: ${(run as Array<Fact<'CORRELATED_EVENT'>>).map((r) => `${w(r.data.eventType)} at ${r.atUtc}`).join('; ')}.`, ...run.map((r) => r.id));
      } else {
        push(
          `Detections recorded with this alarm: ${(run as Array<Fact<'DETECTION'>>).map((r) => `${q(r.data.label)} with confidence ${num(r.data.confidence)} at ${r.atUtc}`).join('; ')}.`,
          ...run.map((r) => r.id)
        );
      }
      i = j - 1;
      continue;
    }

    switch (f.kind) {
      case 'ALARM_RAISED':
        push(`At ${f.atUtc} the alarm ${q(f.data.title)} with severity ${w(f.data.severity)} was raised${onCam(f.cameraId)}.${f.data.source === 'JOURNEY' ? ' It was opened from a confirmed journey.' : ''}`, f.id);
        break;
      case 'TRIGGER_EVENT': {
        const d = f.data;
        const cam = onCam(f.cameraId);
        let s: string | null = null;
        if (d.eventType === 'TRIPWIRE_CROSS' && d.trackId && d.direction) s = `At ${f.atUtc} track ${q(d.trackId)} crossed a tripwire in direction ${w(d.direction)}${cam}.`;
        else if (d.eventType === 'LOITERING_DWELL' && d.trackId && d.zoneId && d.dwellSeconds !== null && d.thresholdSeconds !== null)
          s = `At ${f.atUtc} track ${q(d.trackId)} stayed in zone ${q(d.zoneId)} for ${num(d.dwellSeconds)} seconds; the configured threshold is ${num(d.thresholdSeconds)} seconds${cam}.`;
        else if (d.eventType === 'UNATTENDED_OBJECT' && d.trackId && d.zoneId && d.objectClass && d.dwellSeconds !== null && d.thresholdSeconds !== null)
          s = `At ${f.atUtc} a ${w(d.objectClass)} (track ${q(d.trackId)}) lay still in zone ${q(d.zoneId)} with no person near it for ${num(d.dwellSeconds)} seconds; the configured threshold is ${num(d.thresholdSeconds)} seconds${cam}.`;
        else if (d.eventType === 'WRONG_WAY' && d.trackId && d.zoneId) s = `At ${f.atUtc} track ${q(d.trackId)} moved against the allowed direction of zone ${q(d.zoneId)}${cam}.`;
        else if (d.eventType === 'ANPR_MATCH' && d.plateRead) s = `At ${f.atUtc} a number plate was read and a plate match was recorded${cam}; the plate text is withheld from this summary.`;
        else if (d.eventType === 'AI_OBJECT_DETECTED' && d.objectClass && d.confidence !== null) s = `At ${f.atUtc} a model detected ${q(d.objectClass)} with confidence ${num(d.confidence)}${cam}.`;
        else if (d.eventType === 'MOTION') s = `At ${f.atUtc} classical motion detection reported activity${cam}.`;
        push(s ?? `At ${f.atUtc} an event of type ${q(d.eventType)}${d.source ? ` from source ${q(d.source)}` : ''} was recorded${cam}.`, f.id);
        break;
      }
      case 'TRACK_SIGHTING': {
        const d = f.data;
        const zones = d.zones.length ? `, visiting ${d.zones.map((z) => `zone ${q(z.name)} from ${z.enteredUtc} to ${z.exitedUtc}`).join('; ')}` : '';
        push(`Track ${q(d.trackId)} (${w(d.objectClass)}) was seen${onCam(f.cameraId)} from ${d.firstSeenUtc} to ${d.lastSeenUtc}${d.direction ? `, moving ${w(d.direction)}` : ''}${zones}.`, f.id);
        break;
      }
      case 'LINK_CONFIRMED':
        push(`At ${f.atUtc} an operator (user ${q(f.data.userId)}) confirmed by ${f.data.method === 'PLATE' ? 'plate' : 'appearance'} that tracks ${q(f.data.fromTrackId)} and ${q(f.data.toTrackId)} are the same subject.`, f.id);
        break;
      case 'ALARM_REPEATED':
        push(`The alarm was triggered ${num(f.data.occurrences)} times in total, the last at ${f.data.lastActivityUtc}.`, f.id);
        break;
      case 'SECOND_OPINION':
        push(`At ${f.atUtc} the advisory second-opinion model ${w(f.data.modelName)}@${w(f.data.modelVersion)} answered ${f.data.answer} to whether a ${w(f.data.targetClass)} is visible in the picture; this is not a finding.`, f.id);
        break;
      case 'ACKNOWLEDGED':
        push(`At ${f.atUtc} the alarm was acknowledged by user ${q(f.data.userId)}.`, f.id);
        break;
      case 'VERDICT':
        push(`At ${f.atUtc} user ${q(f.data.userId)} recorded the verdict ${f.data.verdict}${f.data.hasReason ? ' with a written reason (not repeated here)' : ''}.`, f.id);
        break;
      case 'RESOLVED':
        push(`At ${f.atUtc} the alarm was resolved by user ${q(f.data.userId)}${f.data.hasNotes ? ', with resolution notes (not repeated here)' : ''}.`, f.id);
        break;
      case 'EVIDENCE_HOLD':
        push(`At ${f.atUtc} an evidence hold was placed${onCam(f.cameraId)} covering ${f.data.windowStartUtc} to ${f.data.windowEndUtc} (status ${w(f.data.status)}).`, f.id);
        break;
    }
  }

  push(CLOSING_STATEMENT_V1);
  return { sentences, text: joinSentences(sentences) };
}

const RENDERERS: Record<string, (f: IncidentSummaryFactsV1) => RenderedSummary> = {
  [INCIDENT_SUMMARY_TEMPLATE_V1]: renderIncidentSummaryV1,
};

export const isKnownTemplate = (version: string): boolean => Object.prototype.hasOwnProperty.call(RENDERERS, version);

export function renderIncidentSummary(facts: IncidentSummaryFactsV1, templateVersion: string): RenderedSummary {
  const r = RENDERERS[templateVersion];
  if (!r) throw new Error(`unknown incident summary template version: ${templateVersion}`);
  return r(facts);
}
